kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: xZjsVnGk4XWhfQEQGo/d+9rykOxiplgsYCwEvM/mV2A=
      - identity: {}
