kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: Z5fZz3+o8vIURuYroWz9sF1ucyS9QI5CideYa65h3Co=
      - identity: {}
